/*==============================================================*/
/* DROITS D'ACCES POUR LA BDD                                 	*/
/*==============================================================*/
/*==============================================================*/
/* Nom de SGBD :  ORACLE Version 11g                            */
/* Date de création :  26/07/2016 16:37:46                      */
/*==============================================================*/

/* http://docs.oracle.com/javadb/10.8.3.0/ref/rrefsqljgrant.html */

-- TABLESPACE
CREATE SMALLFILE TABLESPACE ARIANE 
    DATAFILE 
        'TBSP_Ariane.DBF' SIZE 104857600 	REUSE 
		AUTOEXTEND ON NEXT 104857600 MAXSIZE UNLIMITED 
    DEFAULT NOCOMPRESS 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;
	

-- USER SQL (EN MAJUSCULE)
CREATE USER FREDERIC IDENTIFIED BY afpa2016
	DEFAULT TABLESPACE "ARIANE"
	TEMPORARY TABLESPACE "TEMP";
ALTER USER "FREDERIC"
	DEFAULT TABLESPACE "ARIANE"
	TEMPORARY TABLESPACE "TEMP";
ACCOUNT UNLOCK ;


-- QUOTAS
ALTER USER "FREDERIC" QUOTA UNLIMITED ON ARIANE;
ALTER USER "FREDERIC" QUOTA UNLIMITED ON APEX_1851336378250219;
ALTER USER "FREDERIC" QUOTA UNLIMITED ON APEX_5457999048253711;
ALTER USER "FREDERIC" QUOTA UNLIMITED ON EXAMPLE;
ALTER USER "FREDERIC" QUOTA UNLIMITED ON SYSAUX;
ALTER USER "FREDERIC" QUOTA UNLIMITED ON SYSTEM;
--ALTER USER "FREDERIC" QUOTA UNLIMITED ON TEMP;
ALTER USER "FREDERIC" QUOTA UNLIMITED ON USERS;


-- ROLES
ALTER USER "FREDERIC" DEFAULT ROLE "DBA","DV_MONITOR","CTXAPP","DV_AUDIT_CLEANUP","SPATIAL_CSW_ADMIN","APEX_GRANTS_FOR_NEW_USERS_ROLE","WFS_USR_ROLE","EM_EXPRESS_ALL","WM_ADMIN_ROLE","OLAP_USER","OLAP_XS_ADMIN","DV_SECANALYST","CSW_USR_ROLE","XS_CACHE_ADMIN","GDS_CATALOG_SELECT","SCHEDULER_ADMIN","PROVISIONER","AUDIT_ADMIN","XDB_WEBSERVICES_OVER_HTTP","DV_REALM_RESOURCE","AQ_ADMINISTRATOR_ROLE","DELETE_CATALOG_ROLE","XDB_WEBSERVICES","DV_PUBLIC","LBAC_DBA","XFILES_USER","OPTIMIZER_PROCESSING_RATE","RECOVERY_CATALOG_USER","DV_DATAPUMP_NETWORK_LINK","GSMUSER_ROLE","XFILES_ADMINISTRATOR","GATHER_SYSTEM_STATISTICS","LOGSTDBY_ADMINISTRATOR","GSM_POOLADMIN_ROLE","DV_ADMIN","HS_ADMIN_ROLE","XS_SESSION_ADMIN","DV_GOLDENGATE_ADMIN","IMP_FULL_DATABASE","DV_XSTREAM_ADMIN","DV_PATCH_ADMIN","DATAPUMP_EXP_FULL_DATABASE","EJBCLIENT","HS_ADMIN_EXECUTE_ROLE","JMXSERVER","OLAP_DBA","ADM_PARALLEL_EXECUTE_TASK","JAVAIDPRIV","SELECT_CATALOG_ROLE","JAVADEBUGPRIV","CONNECT","DATAPUMP_IMP_FULL_DATABASE","SODA_APP","OEM_MONITOR","APEX_ADMINISTRATOR_ROLE","GSMADMIN_ROLE","AQ_USER_ROLE","JAVAUSERPRIV","XDB_SET_INVOKER","RECOVERY_CATALOG_OWNER","JAVA_ADMIN","DBFS_ROLE","PDB_DBA","DV_GOLDENGATE_REDO_ACCESS","CDB_DBA","JAVASYSPRIV","HS_ADMIN_SELECT_ROLE","AUDIT_VIEWER","RESOURCE","DV_OWNER","XDB_WEBSERVICES_WITH_PUBLIC","EXECUTE_CATALOG_ROLE","DV_ACCTMGR","DV_REALM_OWNER","EXP_FULL_DATABASE","DV_STREAMS_ADMIN","JAVA_DEPLOY","SPATIAL_WFS_ADMIN","XS_NAMESPACE_ADMIN","XS_RESOURCE","ORDADMIN","AUTHENTICATEDUSER","CAPTURE_ADMIN","OEM_ADVISOR","XDBADMIN","EM_EXPRESS_BASIC";


-- SYSTEM PRIVILEGES
GRANT DEBUG ANY PROCEDURE TO "FREDERIC" WITH ADMIN OPTION;
GRANT GRANT ANY PRIVILEGE TO "FREDERIC" WITH ADMIN OPTION;
GRANT GRANT ANY ROLE TO "FREDERIC" WITH ADMIN OPTION;
GRANT ADMINISTER ANY SQL TUNING SET TO "FREDERIC" WITH ADMIN OPTION;
GRANT ADMINISTER RESOURCE MANAGER TO "FREDERIC" WITH ADMIN OPTION;
GRANT ADMINISTER SQL TUNING SET TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE ANY MEASURE FOLDER TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE ANY SEQUENCE TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE MEASURE FOLDER TO "FREDERIC" WITH ADMIN OPTION;
GRANT UPDATE ANY CUBE BUILD PROCESS TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE VIEW TO "FREDERIC" WITH ADMIN OPTION;
GRANT ALTER DATABASE LINK TO "FREDERIC" WITH ADMIN OPTION;
GRANT ALTER ANY ASSEMBLY TO "FREDERIC" WITH ADMIN OPTION;
GRANT ALTER ANY SQL TRANSLATION PROFILE TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE ANY EVALUATION CONTEXT TO "FREDERIC" WITH ADMIN OPTION;
GRANT SELECT ANY MINING MODEL TO "FREDERIC" WITH ADMIN OPTION;
GRANT DELETE ANY CUBE DIMENSION TO "FREDERIC" WITH ADMIN OPTION;
GRANT ALTER ANY TABLE TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE SESSION TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE RULE TO "FREDERIC" WITH ADMIN OPTION;
GRANT BECOME USER TO "FREDERIC" WITH ADMIN OPTION;
GRANT SELECT ANY CUBE BUILD PROCESS TO "FREDERIC" WITH ADMIN OPTION;
GRANT SELECT ANY TABLE TO "FREDERIC" WITH ADMIN OPTION;
GRANT INSERT ANY MEASURE FOLDER TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE ANY SQL PROFILE TO "FREDERIC" WITH ADMIN OPTION;
GRANT FORCE ANY TRANSACTION TO "FREDERIC" WITH ADMIN OPTION;
GRANT DELETE ANY TABLE TO "FREDERIC" WITH ADMIN OPTION;
GRANT ALTER ANY SEQUENCE TO "FREDERIC" WITH ADMIN OPTION;
GRANT SELECT ANY CUBE DIMENSION TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE ANY EDITION TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE EXTERNAL JOB TO "FREDERIC" WITH ADMIN OPTION;
GRANT EM EXPRESS CONNECT TO "FREDERIC" WITH ADMIN OPTION;
GRANT DROP ANY MATERIALIZED VIEW TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE ANY CUBE BUILD PROCESS TO "FREDERIC" WITH ADMIN OPTION;
GRANT FLASHBACK ANY TABLE TO "FREDERIC" WITH ADMIN OPTION;
GRANT DROP ANY RULE SET TO "FREDERIC" WITH ADMIN OPTION;
GRANT BACKUP ANY TABLE TO "FREDERIC" WITH ADMIN OPTION;
GRANT ALTER ANY CUBE TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE CREDENTIAL TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE TABLE TO "FREDERIC" WITH ADMIN OPTION;
GRANT EXECUTE ANY LIBRARY TO "FREDERIC" WITH ADMIN OPTION;
GRANT DROP ANY OUTLINE TO "FREDERIC" WITH ADMIN OPTION;
GRANT EXECUTE ASSEMBLY TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE ANY DIMENSION TO "FREDERIC" WITH ADMIN OPTION;
GRANT DROP ANY TABLE TO "FREDERIC" WITH ADMIN OPTION;
GRANT ADMINISTER KEY MANAGEMENT TO "FREDERIC" WITH ADMIN OPTION;
GRANT ALTER ANY CLUSTER TO "FREDERIC" WITH ADMIN OPTION;
GRANT EXECUTE ANY CLASS TO "FREDERIC" WITH ADMIN OPTION;
GRANT ALTER ANY CUBE BUILD PROCESS TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE ANY CREDENTIAL TO "FREDERIC" WITH ADMIN OPTION;
GRANT DROP ANY DIMENSION TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE ANY RULE SET TO "FREDERIC" WITH ADMIN OPTION;
GRANT SELECT ANY SEQUENCE TO "FREDERIC" WITH ADMIN OPTION;
GRANT UNDER ANY TYPE TO "FREDERIC" WITH ADMIN OPTION;
GRANT MANAGE TABLESPACE TO "FREDERIC" WITH ADMIN OPTION;
GRANT DROP ANY OPERATOR TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE ANY OPERATOR TO "FREDERIC" WITH ADMIN OPTION;
GRANT EXEMPT IDENTITY POLICY TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE TYPE TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE TABLESPACE TO "FREDERIC" WITH ADMIN OPTION;
GRANT SELECT ANY TRANSACTION TO "FREDERIC" WITH ADMIN OPTION;
GRANT DELETE ANY MEASURE FOLDER TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE ANY CUBE TO "FREDERIC" WITH ADMIN OPTION;
GRANT LOCK ANY TABLE TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE EVALUATION CONTEXT TO "FREDERIC" WITH ADMIN OPTION;
GRANT DROP ANY TYPE TO "FREDERIC" WITH ADMIN OPTION;
GRANT ADVISOR TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE PUBLIC DATABASE LINK TO "FREDERIC" WITH ADMIN OPTION;
GRANT ANALYZE ANY TO "FREDERIC" WITH ADMIN OPTION;
GRANT DROP ANY RULE TO "FREDERIC" WITH ADMIN OPTION;
GRANT INSERT ANY CUBE DIMENSION TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE ROLLBACK SEGMENT TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE ANY JOB TO "FREDERIC" WITH ADMIN OPTION;
GRANT ALTER USER TO "FREDERIC" WITH ADMIN OPTION;
GRANT QUERY REWRITE TO "FREDERIC" WITH ADMIN OPTION;
GRANT SELECT ANY DICTIONARY TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE PUBLIC SYNONYM TO "FREDERIC" WITH ADMIN OPTION;
GRANT GLOBAL QUERY REWRITE TO "FREDERIC" WITH ADMIN OPTION;
GRANT ALTER ANY CUBE DIMENSION TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE ANY CUBE DIMENSION TO "FREDERIC" WITH ADMIN OPTION;
GRANT DROP ANY CLUSTER TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE ANY RULE TO "FREDERIC" WITH ADMIN OPTION;
GRANT UPDATE ANY CUBE DIMENSION TO "FREDERIC" WITH ADMIN OPTION;
GRANT ADMINISTER RESOURCE MANAGER TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE ANY SYNONYM TO "FREDERIC" WITH ADMIN OPTION;
GRANT DROP ANY SYNONYM TO "FREDERIC" WITH ADMIN OPTION;
GRANT DROP ANY MINING MODEL TO "FREDERIC" WITH ADMIN OPTION;
GRANT EXECUTE ANY PROCEDURE TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE SYNONYM TO "FREDERIC" WITH ADMIN OPTION;
GRANT SET CONTAINER TO "FREDERIC" WITH ADMIN OPTION;
GRANT EXECUTE ANY PROGRAM TO "FREDERIC" WITH ADMIN OPTION;
GRANT EXEMPT REDACTION POLICY TO "FREDERIC" WITH ADMIN OPTION;
GRANT EXECUTE ANY TYPE TO "FREDERIC" WITH ADMIN OPTION;
GRANT ON COMMIT REFRESH TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE SEQUENCE TO "FREDERIC" WITH ADMIN OPTION;
GRANT SELECT ANY MEASURE FOLDER TO "FREDERIC" WITH ADMIN OPTION;
GRANT COMMENT ANY MINING MODEL TO "FREDERIC" WITH ADMIN OPTION;
GRANT ADMINISTER SQL TUNING SET TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE ANY INDEXTYPE TO "FREDERIC" WITH ADMIN OPTION;
GRANT KEEP DATE TIME TO "FREDERIC" WITH ADMIN OPTION;
GRANT DROP ANY INDEX TO "FREDERIC" WITH ADMIN OPTION;
GRANT RESTRICTED SESSION TO "FREDERIC" WITH ADMIN OPTION;
GRANT DEQUEUE ANY QUEUE TO "FREDERIC" WITH ADMIN OPTION;
GRANT ANALYZE ANY DICTIONARY TO "FREDERIC" WITH ADMIN OPTION;
GRANT ALTER ANY INDEXTYPE TO "FREDERIC" WITH ADMIN OPTION;
GRANT TRANSLATE ANY SQL TO "FREDERIC" WITH ADMIN OPTION;
GRANT ADMINISTER ANY SQL TUNING SET TO "FREDERIC" WITH ADMIN OPTION;
GRANT EXEMPT DDL REDACTION POLICY TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE USER TO "FREDERIC" WITH ADMIN OPTION;
GRANT EXECUTE ANY OPERATOR TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE CUBE BUILD PROCESS TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE PROFILE TO "FREDERIC" WITH ADMIN OPTION;
GRANT ALTER ANY ROLE TO "FREDERIC" WITH ADMIN OPTION;
GRANT UPDATE ANY TABLE TO "FREDERIC" WITH ADMIN OPTION;
GRANT ALTER ANY LIBRARY TO "FREDERIC" WITH ADMIN OPTION;
GRANT DROP ANY VIEW TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE ANY CLUSTER TO "FREDERIC" WITH ADMIN OPTION;
GRANT EXECUTE ANY RULE TO "FREDERIC" WITH ADMIN OPTION;
GRANT ALTER TABLESPACE TO "FREDERIC" WITH ADMIN OPTION;
GRANT UNDER ANY VIEW TO "FREDERIC" WITH ADMIN OPTION;
GRANT EXECUTE ANY ASSEMBLY TO "FREDERIC" WITH ADMIN OPTION;
GRANT GRANT ANY PRIVILEGE TO "FREDERIC" WITH ADMIN OPTION;
GRANT ALTER ANY TRIGGER TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE ANY VIEW TO "FREDERIC" WITH ADMIN OPTION;
GRANT EXPORT FULL DATABASE TO "FREDERIC" WITH ADMIN OPTION;
GRANT ALTER ANY MEASURE FOLDER TO "FREDERIC" WITH ADMIN OPTION;
GRANT ALTER ANY EVALUATION CONTEXT TO "FREDERIC" WITH ADMIN OPTION;
GRANT FLASHBACK ARCHIVE ADMINISTER TO "FREDERIC" WITH ADMIN OPTION;
GRANT IMPORT FULL DATABASE TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE ANY OUTLINE TO "FREDERIC" WITH ADMIN OPTION;
GRANT COMMENT ANY TABLE TO "FREDERIC" WITH ADMIN OPTION;
GRANT EXEMPT DML REDACTION POLICY TO "FREDERIC" WITH ADMIN OPTION;
GRANT READ ANY TABLE TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE DATABASE LINK TO "FREDERIC" WITH ADMIN OPTION;
GRANT DROP PUBLIC SYNONYM TO "FREDERIC" WITH ADMIN OPTION;
GRANT DROP USER TO "FREDERIC" WITH ADMIN OPTION;
GRANT CHANGE NOTIFICATION TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE MINING MODEL TO "FREDERIC" WITH ADMIN OPTION;
GRANT INSERT ANY TABLE TO "FREDERIC" WITH ADMIN OPTION;
GRANT DROP PROFILE TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE ANY MATERIALIZED VIEW TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE RULE SET TO "FREDERIC" WITH ADMIN OPTION;
GRANT EXEMPT ACCESS POLICY TO "FREDERIC" WITH ADMIN OPTION;
GRANT MANAGE SCHEDULER TO "FREDERIC" WITH ADMIN OPTION;
GRANT READ ANY FILE GROUP TO "FREDERIC" WITH ADMIN OPTION;
GRANT FORCE TRANSACTION TO "FREDERIC" WITH ADMIN OPTION;
GRANT DROP ANY CUBE BUILD PROCESS TO "FREDERIC" WITH ADMIN OPTION;
GRANT ALTER ANY TYPE TO "FREDERIC" WITH ADMIN OPTION;
GRANT DROP ANY PROCEDURE TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE ANY SQL TRANSLATION PROFILE TO "FREDERIC" WITH ADMIN OPTION;
GRANT DROP PUBLIC DATABASE LINK TO "FREDERIC" WITH ADMIN OPTION;
GRANT DROP ANY INDEXTYPE TO "FREDERIC" WITH ADMIN OPTION;
GRANT DROP ANY SQL PROFILE TO "FREDERIC" WITH ADMIN OPTION;
GRANT ALTER SYSTEM TO "FREDERIC" WITH ADMIN OPTION;
GRANT DROP ANY ROLE TO "FREDERIC" WITH ADMIN OPTION;
GRANT ALTER ANY DIMENSION TO "FREDERIC" WITH ADMIN OPTION;
GRANT DROP ANY CUBE DIMENSION TO "FREDERIC" WITH ADMIN OPTION;
GRANT DROP ANY CUBE TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE ANY TRIGGER TO "FREDERIC" WITH ADMIN OPTION;
GRANT DROP ANY ASSEMBLY TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE ANY TABLE TO "FREDERIC" WITH ADMIN OPTION;
GRANT ADMINISTER SQL MANAGEMENT OBJECT TO "FREDERIC" WITH ADMIN OPTION;
GRANT DROP ANY DIRECTORY TO "FREDERIC" WITH ADMIN OPTION;
GRANT ENQUEUE ANY QUEUE TO "FREDERIC" WITH ADMIN OPTION;
GRANT DROP ANY EVALUATION CONTEXT TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE ANY ASSEMBLY TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE ANY TYPE TO "FREDERIC" WITH ADMIN OPTION;
GRANT REDEFINE ANY TABLE TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE CLUSTER TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE ANY CONTEXT TO "FREDERIC" WITH ADMIN OPTION;
GRANT EXECUTE ANY EVALUATION CONTEXT TO "FREDERIC" WITH ADMIN OPTION;
GRANT RESUMABLE TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE ANY LIBRARY TO "FREDERIC" WITH ADMIN OPTION;
GRANT DROP ANY EDITION TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE PROCEDURE TO "FREDERIC" WITH ADMIN OPTION;
GRANT ALTER DATABASE TO "FREDERIC" WITH ADMIN OPTION;
GRANT SELECT ANY CUBE TO "FREDERIC" WITH ADMIN OPTION;
GRANT GRANT ANY ROLE TO "FREDERIC" WITH ADMIN OPTION;
GRANT ALTER ANY RULE TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE CUBE DIMENSION TO "FREDERIC" WITH ADMIN OPTION;
GRANT ALTER ANY OPERATOR TO "FREDERIC" WITH ADMIN OPTION;
GRANT CREATE CUBE TO "FREDERIC" WITH ADMIN OPTION;
GRANT ALTER RESOURCE COST TO "FREDERIC" WITH ADMIN OPTION;
GRANT DROP TABLESPACE TO "FREDERIC" WITH ADMIN OPTION;
GRANT ALTER ROLLBACK SEGMENT TO "FREDERIC" WITH ADMIN OPTION;
GRANT PURGE DBA_RECYCLEBIN TO "FREDERIC" WITH ADMIN OPTION;

-- Les rôles suivant ne peuvent pas etre appliqués directement :
--GRANT SYSKM TO "FREDERIC" WITH ADMIN OPTION;;
--GRANT SYSBACKUP TO "FREDERIC" WITH ADMIN OPTION;
--GRANT SYSDBA TO "FREDERIC" WITH ADMIN OPTION;
--GRANT SYSOPER TO "FREDERIC" WITH ADMIN OPTION;
--GRANT SYSDG TO "FREDERIC" WITH ADMIN OPTION;
