/*==============================================================*/
/* DROITS D'ACCES POUR LA BDD : ROLES                          	*/
/*==============================================================*/
/* http://docs.oracle.com/javadb/10.8.3.0/ref/rrefsqljgrant.html */
/* http://oracle.developpez.com/guide/administration/adminrole/ */


/*Les effectifs d’ABI sont composés de :

	- Une direction :
	o Un directeur général, administratif et financier
*	o Un responsable des ressources humaines 
*	o Un responsable commercial
	o Un secrétariat administratif (1 personne)

	- Un département opérationnel composé de :
*	o Un responsable du département études
	o Des ingénieurs d’études (20 personnes)
*		 Chefs de projet
		 Analystes
		 Développeurs
*	o Un secrétariat technique (2 personnes)
	o Des techniciens supports (5 personnes)
	o Des commerciaux (2 personnes)
*/

/* --EXEMPLE POUR LA CREATION DES ROLES :
CREATE ROLE Nom_Role ;
GRANT SELECT, INSERT, UPDATE, DELETE ON Nom_Schema.Nom_Table1 TO Nom_Role ;
GRANT SELECT, INSERT, UPDATE, DELETE ON Nom_Schema.Nom_Table2 TO Nom_Role ;
GRANT Nom_Role TO Nom_Utilisateur ;
--DROP ROLE Nom_Role ;
*/-- CREATION ROLES

CREATE ROLE RESP_COM ;		-- Responsable commercial (1)
GRANT SELECT ON CDI10.COLLABORATEURS TO RESP_COM ;
GRANT SELECT, INSERT, UPDATE ON CDI10.CLIENTS TO RESP_COM ;
GRANT SELECT, INSERT, UPDATE ON CDI10.LIBDOMACTIVITES TO RESP_COM ;
GRANT SELECT, INSERT, UPDATE ON CDI10.CLIDOMAINE TO RESP_COM ;
GRANT SELECT, INSERT, UPDATE ON CDI10.CONTACTS TO RESP_COM ;
GRANT SELECT, INSERT, UPDATE ON CDI10.INTERVENIR TO RESP_COM ;
GRANT SELECT, INSERT, UPDATE ON CDI10.COLLABORER TO RESP_COM ;
GRANT SELECT, INSERT, UPDATE ON CDI10.CLICOMMENTER TO RESP_COM ;
GRANT SELECT, INSERT, UPDATE ON CDI10.PROCOMMENTER TO RESP_COM ;

CREATE ROLE RESP_ETD ;		-- Responsable du département études (1)
GRANT GRANT ANY ROLE TO RESP_ETD WITH ADMIN OPTION;
GRANT SELECT ON CDI10.COLLABORATEURS TO RESP_ETD ;
GRANT SELECT, INSERT, UPDATE ON CDI10.PROJETS TO RESP_ETD ;
GRANT SELECT, INSERT, UPDATE ON CDI10.LIBRETEXP TO RESP_ETD ;
GRANT SELECT ON CDI10.RETOURSEXP TO RESP_ETD ;
GRANT SELECT, INSERT, UPDATE ON CDI10.LIBETAPES TO RESP_ETD ;
GRANT SELECT, INSERT, UPDATE ON CDI10.ETAPES TO RESP_ETD ;
GRANT SELECT, INSERT, UPDATE ON CDI10.COLLABORER TO RESP_ETD ;
GRANT SELECT, INSERT, UPDATE ON CDI10.INTERVENIR TO RESP_ETD ;
GRANT SELECT ON CDI10.CONTACTS TO RESP_ETD ;
GRANT SELECT ON CDI10.DOCUMENTS TO RESP_ETD ;
GRANT SELECT ON CDI10.REFERERDOC TO RESP_ETD ;
GRANT SELECT, INSERT ON CDI10.CONTACTS TO RESP_ETD ;
-- Associe role chef_projet a un collaborateur (et donc retire aussi ce droit)

CREATE ROLE RESP_RRH ;		-- Responsable des Ressources Humaines (1)
GRANT CREATE USER TO RESP_RRH WITH ADMIN OPTION;
GRANT ALTER USER TO RESP_RRH WITH ADMIN OPTION;
GRANT GRANT ANY ROLE TO RESP_RRH WITH ADMIN OPTION;
GRANT SELECT, INSERT, UPDATE ON CDI10.COLLABORATEURS TO RESP_RRH ;
GRANT SELECT, INSERT, UPDATE ON CDI10.LIBFONCTIONS TO RESP_RRH ;
GRANT SELECT, INSERT, UPDATE ON CDI10.OCCUPERFONCTIONS TO RESP_RRH ;
GRANT SELECT ON CDI10.COLLABORER TO RESP_RRH ;
GRANT SELECT ON CDI10.SALAIRES TO RESP_RRH ;

CREATE ROLE SECR_TECH ;		-- Secrétariat technique (2)
GRANT SELECT ON CDI10.COLLABORATEURS TO SECR_TECH ;
GRANT SELECT, UPDATE ON CDI10.PROJETS TO SECR_TECH ;
GRANT SELECT ON CDI10.DOCUMENTS TO SECR_TECH ;
GRANT SELECT, INSERT ON CDI10.REFERERDOC TO SECR_TECH ;

CREATE CHEF_PROJET ;		-- Chefs de projet (0-20)
GRANT SELECT ON CDI10.COLLABORATEURS TO CHEF_PROJET ;
GRANT SELECT ON CDI10.PROJETS TO CHEF_PROJET ;
GRANT SELECT, INSERT, UPDATE ON CDI10.INTERVENIR TO CHEF_PROJET ;
GRANT SELECT ON CDI10.LIBETAPES TO CHEF_PROJET ;
GRANT SELECT, INSERT, UPDATE ON CDI10.ETAPES TO CHEF_PROJET ;
GRANT SELECT ON CDI10.LIBRETEXP TO CHEF_PROJET ;
GRANT SELECT, INSERT, UPDATE ON CDI10.RETOURSEXP TO CHEF_PROJET ;

CREATE COLLABORATEUR ;		-- Collaborateurs (5-*)
GRANT SELECT, INSERT, UPDATE ON CDI10.DOCUMENTS TO COLLABORATEUR ;
GRANT SELECT, INSERT ON CDI10.PROCOMMENTER TO COLLABORATEUR ;





