/*	PROCÉDURES STOCKÉES
-- https://docs.oracle.com/cd/B19306_01/server.102/b14200/statements_6009.htm
-- https://docs.oracle.com/cd/B28359_01/appdev.111/b28843/tdddg_procedures.htm
*/---------------------------------------------------------------------------

/* Attribuer le role de CHEF DE PROJET à un collaborateur */
CREATE OR REPLACE PROCEDURE ChefProjet_Attribuer (USER_LOGIN VARCHAR2) IS
BEGIN 
	GRANT CHEF_PROJET TO USER_LOGIN;
END; 

---------------------------------------------------------------------------
/* Revoquer le droit au role de CHEF DE PROJET à un collaborateur */
CREATE OR REPLACE PROCEDURE ChefProjet_Retirer (USER_LOGIN VARCHAR2) IS
BEGIN 
	REVOKE CHEF_PROJET TO USER_LOGIN;
END; 

---------------------------------------------------------------------------
-- Création d'une vue matérialisée :
CREATE OR REPLACE PROCEDURE CREATE_VM_OCCUPERFONCTIONS IS
BEGIN 
  EXECUTE IMMEDIATE 'CREATE MATERIALIZED VIEW TEMP_OCCUPERFONCTIONS BUILD IMMEDIATE REFRESH FAST ON COMMIT AS SELECT * FROM OCCUPERFONCTIONS WHERE COL_MATRICULE = :NEW.COL_MATRICULE';
  EXECUTE IMMEDIATE 'INSERT INTO TEMP_OCCUPERFONCTIONS (COL_MATRICULE, FONCTION_ID, COL_TYPECONTRAT, COL_DATEEMBAUCHE, COL_DATEFINCONTRAT, COL_SALAIREBASE) VALUES (:NEW.COL_MATRICULE, :NEW.FONCTION_ID, :NEW.COL_TYPECONTRAT, :NEW.COL_DATEEMBAUCHE, :NEW.COL_DATEFINCONTRAT, :NEW.COL_SALAIREBASE);';
  EXECUTE IMMEDIATE 'SELECT QUERY FROM ALL_MVIEWS WHERE MVIEW_NAME=TEMP_OCCUPERFONCTIONS';
END; 