
/*==============================================================*/
/* JEU D'INSERTION POUR LA BDD                                 	*/
/*==============================================================*/
/*==============================================================*/
/* Nom de SGBD :  ORACLE Version 11g                            */
/* Date de création :  26/07/2016 16:37:46                      */
/*==============================================================*/

/* https://docs.oracle.com/cd/B14117_01/appdev.101/b10807/13_elems025.htm */
/* 
INSERT INTO bonus SELECT ename, job, sal, comm FROM emp
   WHERE comm > sal * 0.25;
...
INSERT INTO emp (empno, ename, job, sal, comm, deptno)
   VALUES (4160, 'STURDEVIN', 'SECURITY GUARD', 2045, NULL, 30);
...
INSERT INTO dept
   VALUES (my_deptno, UPPER(my_dname), 'CHICAGO');
*/
-----------------------------------------------------------------BEGIN
/* COLLABORATEURS */
--DELETE FROM COLLABORATEURS WHERE COL_MATRICULE > 0;
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY'; --AJOUT DATE NAISSANCE
INSERT INTO COLLABORATEURS (COL_MATRICULE,COL_SEXE,COL_ETATCIVIL,COL_NOM,COL_PRENOM,COL_DATENAISSANCE,COL_ADRESSE1,COL_ADRESSE2,COL_VILLE,COL_CP,COL_TELEPHONE,COL_STATUT,COL_ANCIENNETE,COL_CENTRESINTERETS)
  VALUES (1601,'F','MME','Poulain','Amélie','30/12/1980','56 rue des Trois Frères',' ','Paris','75005','0972461483','MARIEE','15','Se meler de la vie des autres');
INSERT INTO COLLABORATEURS (COL_MATRICULE,COL_COL_MATRICULE,COL_SEXE,COL_ETATCIVIL,COL_NOM,COL_PRENOM,COL_DATENAISSANCE,COL_ADRESSE1,COL_ADRESSE2,COL_VILLE,COL_CP,COL_TELEPHONE,COL_STATUT,COL_ANCIENNETE,COL_CENTRESINTERETS) 
  VALUES (1602,1602,'M','MR','Kiok','Michael','30/12/1980','69 rue de la pignolle',' ','Berlin','12627','49123456789','c' || '''' || 'est complixe !','52','Aime prendre des chevaux et sa chienne Cessy');
	UPDATE COLLABORATEURS SET COL_STATUT = 'C'|| '''' ||'est compliqué' WHERE COL_MATRICULE = 1602;
	UPDATE COLLABORATEURS SET COL_COL_MATRICULE = 1601 WHERE COL_MATRICULE = 1602;
INSERT INTO COLLABORATEURS (COL_MATRICULE,COL_SEXE,COL_ETATCIVIL,COL_NOM,COL_PRENOM,COL_DATENAISSANCE,COL_ADRESSE1,COL_ADRESSE2,COL_VILLE,COL_CP,COL_TELEPHONE,COL_STATUT,COL_ANCIENNETE,COL_CENTRESINTERETS)
  VALUES (1603,'F','MME','Croft','Lara','30/12/1980','Manoir Croft','Restricted Area','Etat-Unis','INCONNU','INCONNU','CELIB','20','Augmenter son tour de poitrine');
INSERT INTO COLLABORATEURS (COL_MATRICULE,COL_COL_MATRICULE,COL_SEXE,COL_ETATCIVIL,COL_NOM,COL_PRENOM,COL_DATENAISSANCE,COL_ADRESSE1,COL_ADRESSE2,COL_VILLE,COL_CP,COL_TELEPHONE,COL_STATUT,COL_ANCIENNETE,COL_CENTRESINTERETS)
  VALUES (1604,1602,'M','MR','Castor','Père','30/12/1980','Dans un arbre','Dans son canapé','Foret','54000','Par pigeon','VEUF','87','Raconter des histoires');
--SELECT * FROM CDI10.COLLABORATEURS ORDER BY COL_MATRICULE;
-----------------------------------------------------------------OK
/* SALAIRES */
-- --SALAIRE_ID n'est pas obligatoire car géré par un TRIGGER
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY/MM/DD HH24:MI:SS';
INSERT INTO SALAIRES (SALAIRE_ID,COL_MATRICULE,SALAIRE_MENSUEL,SALAIRE_DATE)
  VALUES (S_SALAIRES.nextval, 1601, '1300,48', '2016/07/27 14:53:45');  
INSERT INTO SALAIRES VALUES (S_SALAIRES.nextval, 1602, '1500,00', '2016/07/27 14:55:45');
--INSERT INTO SALAIRES VALUES (S_SALAIRES.nextval, 1602, '1500,00', '2016/07/27 14:55:45');
--DELETE FROM SALAIRES WHERE COL_MATRICULE=1602 AND SALAIRE_ID > 2;
INSERT INTO SALAIRES VALUES (S_SALAIRES.nextval, 1603, '9000,00', '2016/07/27 14:56:45');
INSERT INTO SALAIRES VALUES (S_SALAIRES.nextval, 1604, '600,00', '2016/07/27 14:57:45');
--DELETE FROM SALAIRES WHERE SALAIRE_ID = 5;
--SELECT * FROM CDI10.SALAIRES ORDER BY SALAIRE_DATE;
-----------------------------------------------------------------OK
/* LIBFONCTIONS */
INSERT INTO LIBFONCTIONS (FONCTION_ID,FONCTION_LIBELLE)
 VALUES (S_LIBFONCTIONS.nextval, 'Developpeur');  
 -- d'autres ajouts a faire pour alimenter la base ! =)
--SELECT * FROM CDI10.LIBFONCTIONS;
-----------------------------------------------------------------OK
/* OCCUPERFONCTIONS */
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY/MM/DD HH24:MI:SS';
INSERT INTO OCCUPERFONCTIONS (COL_MATRICULE,FONCTION_ID,COL_TYPECONTRAT,COL_DATEEMBAUCHE,COL_DATEFINCONTRAT,COL_SALAIREBASE)
 VALUES (1601, 1, 'CDD', '2016/07/28 09:00:00', '2017/07/28 09:00:00', '1300,48');  
 -- d'autres ajouts a faire pour alimenter la base ! =)
--SELECT * FROM CDI10.OCCUPERFONCTIONS;
-----------------------------------------------------------------OK
/* LIBDOMACTIVITES */
INSERT INTO LIBDOMACTIVITES (CLI_DOMAINEID,CLI_DOMAINEACTIVITE)
 VALUES (S_LIBDOMACTIVITES.nextval, 'Agro-Alimentaire');  
 -- d'autres ajouts a faire pour alimenter la base ! =)
--SELECT * FROM CDI10.LIBDOMACTIVITES;
-----------------------------------------------------------------OK
/* CLIENTS */
INSERT INTO CLIENTS (CLI_NUMCLIENT,CLI_NOM,CLI_RAISONSOCIALE,CLI_TYPE,CLI_ADRESSE,CLI_TELEPHONE,CLI_CHIFFREAFFAIRE,CLI_EFFECTIFS,CLI_NATURE)
 VALUES (1601, 'NaturalFood', 'SARL', 'Pr', '20 rue de la cambrousse 00000 Neverland', '0123456789',10,35,'principale');  
 -- Creer aussi directement la liaison avec son domaine d'activite ! > CLIDOMAINE
--SELECT * FROM CDI10.CLIENTS;
-----------------------------------------------------------------OK
/* CLIDOMAINE */
INSERT INTO CLIDOMAINE (CLI_NUMCLIENT,CLI_DOMAINEID)
 VALUES (1601, 1);  
 -- d'autres ajouts a faire pour alimenter la base ! =)
--SELECT * FROM CDI10.CLIDOMAINE; 
-----------------------------------------------------------------OK
/* CLICOMMENTER */
--SELECT COL_MATRICULE FROM CDI10.COLLABORATEURS ORDER BY COL_MATRICULE;
--SELECT CLI_NUMCLIENT FROM CDI10.CLIENTS;
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY/MM/DD HH24:MI:SS';
INSERT INTO CLICOMMENTER (COL_MATRICULE,CLI_NUMCLIENT,COMCLI_COMCLIENT,COMCLI_DATETIME) VALUES 
	(1601,1601,'Je me fourni en concombre et gros navet la bas !','2016/04/21 11:45:10');
INSERT INTO CLICOMMENTER (COL_MATRICULE,CLI_NUMCLIENT,COMCLI_COMCLIENT,COMCLI_DATETIME) VALUES 
	(1602,1601,'Ils ne possedent que des vaches, dommage...','2016/05/24 13:45:20');
INSERT INTO CLICOMMENTER (COL_MATRICULE,CLI_NUMCLIENT,COMCLI_COMCLIENT,COMCLI_DATETIME) VALUES 
	(1603,1601,'Ne possède aucune relique... :/','2016/06/27 13:45:30');
INSERT INTO CLICOMMENTER (COL_MATRICULE,CLI_NUMCLIENT,COMCLI_COMCLIENT,COMCLI_DATETIME) VALUES 
	(1604,1601,'Laissez moi vous raconter cette histoire...','2016/07/29 13:45:40');
--SELECT * FROM CDI10.CLICOMMENTER;
-----------------------------------------------------------------OK
/* PROJETS */
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY/MM/DD HH24:MI:SS';
INSERT INTO PROJETS (PROJET_CODE,CLI_NUMCLIENT,PROJET_LIBELLECOURT,PROJET_LIBELLELONG,PROJET_TYPE,
	PROJET_CYCLEVIE,PROJET_SECTEURACTIVITE,PROJET_DATEPREVUEDEBUT,PROJET_DATEPREVUEFIN,PROJET_CHARGEGLOBALEESTIMEE) 
	VALUES (1601,1601,'Site E-Commerce','Presentation produits et ventes','F',
			'COMPLET','Commerce','2016/07/29 11:35:00','2016/10/29 11:35:00',500);
UPDATE PROJETS SET PROJET_DATEREELLEDEBUT = '2016/08/01 00:00:00' WHERE PROJET_CODE = 1601;
--DELETE FROM PROJETS WHERE PROJET_CODE > 1;
--SELECT * FROM CDI10.PROJETS;
-----------------------------------------------------------------OK
/* CONTACTS */
--SELECT * FROM CDI10.CLIENTS;
--SELECT * FROM CDI10.PROJETS;
INSERT INTO CONTACTS (CLI_NUMCLIENT,PROJET_CODE,CON_FONCTION,CON_NOM,CON_PRENOM) 
	VALUES (1601,1601,'Roi du Nord','Snow','Jon');
--SELECT * FROM CDI10.CONTACTS;
-----------------------------------------------------------------OK
/* DOCUMENTS */
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY/MM/DD HH24:MI:SS';
INSERT INTO DOCUMENTS (DOC_ID,COL_MATRICULE,DOC_TITRE,DOC_RESUME,DOC_DATEDIFFUSION) 
	VALUES (S_DOCUMENTS.nextval,1601,'Le roi est mort ! Vive le roi !','Roi des sandales et des premiers sommes','2016/10/29 11:35:00');
INSERT INTO DOCUMENTS (COL_MATRICULE,DOC_TITRE,DOC_RESUME,DOC_DATEDIFFUSION)
	VALUES (1601, 'Cher journal', 'Notes concernant les voisins...','2016/07/27 15:23:45');  
-- Il faut aussi créer directement la relation entre le projet et le document : REFERERDOC
--SELECT * FROM CDI10.DOCUMENTS;
-----------------------------------------------------------------OK
/* REFERERDOC */
--SELECT * FROM CDI10.DOCUMENTS;
--SELECT * FROM CDI10.PROJETS;
INSERT INTO CONTACTS (DOC_ID,PROJET_CODE) VALUES (1,1601);
--SELECT * FROM CDI10.CONTACTS;
-----------------------------------------------------------------OK
/* PROCOMMENTER */
--SELECT * FROM CDI10.CLIENTS;
--SELECT * FROM CDI10.COLLABORATEURS ORDER BY COL_MATRICULE;
--SELECT * FROM CDI10.PROJETS;
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY/MM/DD HH24:MI:SS';
INSERT INTO PROCOMMENTER (CLI_NUMCLIENT,COL_MATRICULE,PROJET_CODE,COMPRO_COMPROJET,COMPRO_DATETIME) 
	VALUES (1601,1601,1601,'Que va devenir Arya ?','2016/08/02 15:23:45');
--SELECT * FROM CDI10.PROCOMMENTER;
-----------------------------------------------------------------OK
/* LIBETAPES */
INSERT INTO LIBETAPES (STEP_LIBELLE) VALUES ('ETUDES');
-- Section pouvant etre alimenté pour jeu d'essai !
--SELECT * FROM CDI10.LIBETAPES;
-----------------------------------------------------------------OK
/* ETAPES */
--SELECT * FROM CDI10.LIBETAPES;
--SELECT * FROM CDI10.PROJETS;
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY/MM/DD HH24:MI:SS';
INSERT INTO ETAPES (STEP_ID,PROJET_CODE,CHARGE_ESTIMEEINITIAL,CHARGE_DATEDEBUT) 
	VALUES (1,1601,11,'2016/08/02 10:00:00');
UPDATE ETAPES SET CHARGE_REELLESPROD = 12, CHARGE_DATEFIN = '2016/08/04 15:23:45', CHARGE_VALIDATION = 12 WHERE CHARGE_NUMLOT = 160101;
--SELECT * FROM CDI10.ETAPES;
-----------------------------------------------------------------OK
/* INTERVENIR */
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY/MM/DD HH24:MI:SS';
INSERT INTO INTERVENIR (FONCTION_ID,CHARGE_NUMLOT,COL_MATRICULE,INT_DATEDEBUT) VALUES (1,160101,1601,'2016/08/02 10:30:00');
UPDATE INTERVENIR SET INT_DOMAINEINTER='DEV',INT_TYPEACTIVITE='Debug',INT_DATEFIN='2016/08/02 11:30:00' WHERE CHARGE_NUMLOT = 160101;
--SELECT * FROM CDI10.INTERVENIR;
-----------------------------------------------------------------OK
/* LIBRETEXP */
INSERT INTO LIBRETEXP (RETEXP_LIBELLE) VALUES ('SGBD');
-- Section pouvant etre alimenté pour jeu d'essai !
--SELECT * FROM CDI10.LIBRETEXP;
-----------------------------------------------------------------OK
/* COLLABORER */
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY/MM/DD HH24:MI:SS';
INSERT INTO COLLABORER (PROJET_CODE,COL_MATRICULE,COLAB_DATE_INTEGRATION,COLAB_EVOLUTION_FONCTION,COLAB_CHEF_PROJET,COLAB_PARTICIPE_TOUJOURS) 
			   VALUES (1601,1601,'2016/08/01 00:00:00','Responsable Bureau Etudes',1,1);
UPDATE COLLABORER SET COLAB_PARTICIPE_TOUJOURS=0 WHERE COLAB_ID = 1;
--SELECT * FROM CDI10.COLLABORER;
-----------------------------------------------------------------OK
/* RETOURSEXP */
--SELECT * FROM CDI10.LIBRETEXP;
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY/MM/DD HH24:MI:SS';
INSERT INTO RETOURSEXP (CHARGE_NUMLOT,COLAB_ID,RETEXP_ID,EXP_DATETIME,EXP_DESCRIPTION) 
			   VALUES (160101,1601,1,'2016/08/01 05:00:00','ORACLE');
--SELECT * FROM CDI10.RETOURSEXP;
-----------------------------------------------------------------OK